server:
  port: 8080
spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/nj-2107?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  thymeleaf:
    cache: false

#myBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qfjy.entity.po
  configuration:
    map-underscore-to-camel-case: true
# log config
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/sanfi-2107/log
