server:
  port: 8085

#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

# log config
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/sanfi-2107/log
spring:
  application:
    name: sanfi-video