server:
  port: 8000

spring:
  application:
    name: sanfi-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
